---
- name: 패키지 업데이트 및 LVM 패키지 설치
  import_tasks: update-packages.yml

- name: LVM 구성
  import_tasks: configure-lvm.yml

- name: 파일시스템 구성
  import_tasks: configure-filesystem.yml

- name: 구성완료된 Logical Volume을 마운팅
  import_tasks: mount-disk.yml
