---
- name: create new group
  group:
    name: "{{ item.new_group }}"
    state: present
  loop: "{{ new_user_infolist }}"

- name: create new user and belonging new_group
  user:
    name: "{{ item.new_username }}"
    password: "{{ item.new_user_password }}"
    group: "{{ item.new_group }}"
    shell: /bin/bash
    state: present
  loop: "{{ new_user_infolist }}"

- name: remove specific user
  user:
    name: "{{ removed_username }}"
    state: absent
    remove: yes
  when: is_remove_user == True

- name: Create a directory if it does not exist for new_user
  ansible.builtin.file:
    path: "{{ item.directory_path }}"
    state: directory
    mode: '0755'
    owner: "{{ item.owner_name }}"
    group: "{{ item.group_name }}"
  loop: "{{ new_directory }}"
